// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Dog struct {
	ID   string `json:"_id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type NewDog struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}
